<x-app-layout>
    <div class="max-w-3xl mx-auto px-6 py-16">

        {{-- Header --}}
        <div class="mb-12">
            <p class="text-xs font-bold text-volt uppercase tracking-[0.2em] mb-3">Legal</p>
            <h1 class="font-heading text-5xl sm:text-6xl text-[#f0ece4] leading-none">TERMS OF <span class="text-volt">SERVICE</span></h1>
            <p class="mt-4 text-xs text-[#555]">Last updated: April 2026</p>
        </div>

        {{-- Body --}}
        <div class="space-y-10 text-sm text-[#bbb] leading-relaxed">

            <p class="text-[#888]">
                By creating an account and using TailorAI, you agree to the following terms. Please read them carefully.
            </p>

            {{-- 1 --}}
            <section>
                <h2 class="font-heading text-2xl text-[#f0ece4] mb-4">1. THE SERVICE</h2>
                <p>
                    TailorAI is an AI-powered resume tailoring tool. You provide a base resume and a job description,
                    and our AI rewrites the resume to be targeted at the specific role and writes a matching cover letter.
                    Output is delivered as a downloadable PDF.
                </p>
            </section>

            {{-- 2 --}}
            <section>
                <h2 class="font-heading text-2xl text-[#f0ece4] mb-4">2. YOUR RESPONSIBILITIES</h2>
                <ul class="space-y-2 list-disc pl-5">
                    <li>You agree not to submit false, misleading, or fraudulent information about your work history, education, or qualifications.</li>
                    <li>You agree not to abuse the service through automated scraping, denial-of-service attempts, or attempts to bypass paywalls or rate limits.</li>
                    <li>You are responsible for keeping your login credentials secure.</li>
                    <li>You must be at least 16 years old to use TailorAI.</li>
                </ul>
            </section>

            {{-- 3 --}}
            <section>
                <h2 class="font-heading text-2xl text-[#f0ece4] mb-4">3. AI DISCLAIMER</h2>
                <div class="bg-[#111] border border-[#1f1f1f] rounded-xl p-5">
                    <p class="text-[#f0ece4]">
                        Content generated by TailorAI is AI-generated and should be reviewed before submission.
                        TailorAI makes no guarantees regarding hiring outcomes.
                    </p>
                </div>
                <p class="mt-4">
                    AI output may occasionally contain inaccuracies or formatting issues. Always read your tailored resume
                    and cover letter carefully before sending them to a prospective employer. The accuracy of factual information
                    (dates, titles, achievements) is your responsibility.
                </p>
            </section>

            {{-- 4 --}}
            <section>
                <h2 class="font-heading text-2xl text-[#f0ece4] mb-4">4. PAYMENT TERMS</h2>
                <ul class="space-y-2 list-disc pl-5">
                    <li>Pay-per-use credits cost <span class="text-volt">$2.99 per credit</span> and never expire.</li>
                    <li>The Unlimited subscription costs <span class="text-volt">$19/month</span> and grants unlimited tailoring while active.</li>
                    <li>Subscriptions can be cancelled any time from the Billing page; access continues until the end of the current billing period.</li>
                    <li><strong class="text-[#f0ece4]">No refunds are issued on used credits or partial subscription periods.</strong> Unused credits remain in your account indefinitely.</li>
                    <li>All payments are processed by Stripe. We do not store card details.</li>
                </ul>
            </section>

            {{-- 5 --}}
            <section>
                <h2 class="font-heading text-2xl text-[#f0ece4] mb-4">5. INTELLECTUAL PROPERTY</h2>
                <p>
                    You retain full ownership of all resume content, work history, and personal information you submit to TailorAI.
                    TailorAI retains ownership of the platform itself, including the software, design, branding, prompts, and infrastructure.
                    The AI-generated output produced for you is yours to use however you see fit.
                </p>
            </section>

            {{-- 6 --}}
            <section>
                <h2 class="font-heading text-2xl text-[#f0ece4] mb-4">6. LIMITATION OF LIABILITY</h2>
                <p>
                    TailorAI is provided "as is" without warranty of any kind. To the maximum extent permitted by law, TailorAI,
                    its operators, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive
                    damages — including but not limited to lost job opportunities, lost wages, or emotional distress — arising from
                    your use of, or inability to use, the service. Our total liability in any matter shall not exceed the amount you
                    have paid TailorAI in the preceding twelve months.
                </p>
            </section>

            {{-- 7 --}}
            <section>
                <h2 class="font-heading text-2xl text-[#f0ece4] mb-4">7. GOVERNING LAW</h2>
                <p>
                    These terms are governed by the laws of the State of <span class="text-[#f0ece4]">North Carolina</span>, United States,
                    without regard to conflict-of-law principles. Any disputes arising from the use of TailorAI shall be resolved in the courts
                    of North Carolina.
                </p>
            </section>

            {{-- 8 --}}
            <section>
                <h2 class="font-heading text-2xl text-[#f0ece4] mb-4">8. CONTACT</h2>
                <p>
                    Questions about these terms? Reach us at
                    <a href="{{ route('support') }}" class="text-volt hover:underline">support@tailorai.com</a>.
                </p>
            </section>

        </div>

        {{-- Footer link --}}
        <div class="mt-16 pt-8 border-t border-[#1f1f1f] flex items-center justify-between text-xs text-[#444]">
            <a href="{{ route('legal.privacy') }}" class="hover:text-[#f0ece4] transition">← Privacy Policy</a>
            <a href="{{ url('/') }}" class="hover:text-[#f0ece4] transition">Back to TailorAI →</a>
        </div>

    </div>
</x-app-layout>
